OasisCommunicationManagement/Controllers/ProductionEmployeesController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OasisCommunicationManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Policy;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Ajax.Utilities;
using System.Web.Services.Description;
using System.Windows.Forms;


namespace OasisCommunicationManagement.Controllers
{
    public class ProductionEmployeesController : Controller
    {
        // GET: ProductionEmployees
        private string OasisConnectionManager;
        private SqlConnection OasisConnection;
        public ActionResult Index()
        {

            List<notificationModel> Noticafition = new List<notificationModel>();

            OasisConnectionManager = ConfigurationManager.ConnectionStrings["OasisConnectionString"].ConnectionString;

            OasisConnection = new SqlConnection(OasisConnectionManager);

            DataTable dataTable = new DataTable();
            OasisConnection.Open();

            var query = "select * from messages where FK_RecieverID=" + Convert.ToInt32(Session["id"]);

            SqlCommand SelectCommand = new SqlCommand(query, OasisConnection);
            int count = 0;
            using (SqlDataReader rd = SelectCommand.ExecuteReader())
            {
                Session["totalMsg"] = rd.FieldCount;

                while (rd.Read())
                {
                    if (rd["MsgStatus"].ToString() == "Sent")
                    {
                        count = count + 1;
                    }

                }

                Session["msgNum"] = count;

            }

            if (OasisConnection.State == ConnectionState.Open)
            {
                OasisConnection.Close();





                OasisConnectionManager = ConfigurationManager.ConnectionStrings["OasisConnectionString"].ConnectionString;

                OasisConnection = new SqlConnection(OasisConnectionManager);

                OasisConnection.Open();

                var queryNotification = "select * from Notifications where RecieverRole='" + "ProductionEmployee" + "'";

                SqlCommand SelectNotificatoinCommand = new SqlCommand(queryNotification, OasisConnection);

                using (SqlDataReader rd = SelectNotificatoinCommand.ExecuteReader())
                {

                    while (rd.Read())
                    {
                        notificationModel notify = new notificationModel();
                        notify.id = Convert.ToInt32(rd["id"]);

                        notify.RecieverRole = rd["RecieverRole"].ToString();
                        notify.Notification = rd["Notification"].ToString();
                        notify.datesent = Convert.ToDateTime(rd["datesent"]);
                        Noticafition.Add(notify);
                    }

                }

            }

            return View(Noticafition);
        }



        public ActionResult NotificationDetail(int NotificationID)
        {

            List<TaskModel> Noticafition = new List<TaskModel>();
            Session["notificationID"] = NotificationID;
            OasisConnectionManager = ConfigurationManager.ConnectionStrings["OasisConnectionString"].ConnectionString;

            OasisConnection = new SqlConnection(OasisConnectionManager);

            DataTable dataTable = new DataTable();
            OasisConnection.Open();

            var query = "select * from Notifications where id='" + NotificationID + "'";

            SqlCommand SelectCommand = new SqlCommand(query, OasisConnection);
            notificationModel notify = new notificationModel();

            using (SqlDataReader rd = SelectCommand.ExecuteReader())
            {

                if (rd.Read())
                {

                    notify.id = Convert.ToInt32(rd["id"]);
                    notify.Fk_TaskID = Convert.ToInt32(rd["Fk_TaskID"]);
                    notify.RecieverRole = rd["RecieverRole"].ToString();
                    notify.Notification = rd["Notification"].ToString();
                    notify.datesent = Convert.ToDateTime(rd["datesent"]);

                    OasisConnection.Close();

                    return View(notify);


                }
                else
                {
                    notify.RecieverRole = "no data";

                    return View(notify);
                }
            }
        }
    

        public ActionResult taskProgress(int NotificationID)
        {

            List<TaskModel> Noticafition = new List<TaskModel>();
            TaskModel notify = new TaskModel();
            Session["notificationID"] = NotificationID;
            OasisConnectionManager = ConfigurationManager.ConnectionStrings["OasisConnectionString"].ConnectionString;

            OasisConnection = new SqlConnection(OasisConnectionManager);

            DataTable dataTable = new DataTable();
            OasisConnection.Open();

            var query = "select Fk_TaskID from Notifications where id='" + NotificationID + "'";

            SqlCommand SelectCommand = new SqlCommand(query, OasisConnection);

            using (SqlDataReader rd = SelectCommand.ExecuteReader())
            {

                if (rd.Read())
                {

                    if (OasisConnection.State == ConnectionState.Open)
                    {
                        var queryTask= "select * from Tasks where id='" + Convert.ToInt32(rd["Fk_TaskID"]) + "'";
                        OasisConnection.Close();

                        SqlCommand SelectTaskCommand = new SqlCommand(queryTask, OasisConnection);
                        OasisConnection.Open();

                        SqlDataReader rdTask = SelectTaskCommand.ExecuteReader();

                        if(rdTask.Read())
                        {
                            notify.id = Convert.ToInt32(rdTask["id"]);

                            notify.TaskStatus = rdTask["TaskStatus"].ToString();
                            notify.Taskdetail = rdTask["Taskdetail"].ToString();
                            notify.dateAssigned = Convert.ToDateTime(rdTask["dateAssigned"]);
                            notify.DueDate = Convert.ToDateTime(rdTask["DueDate"]);

                            if (rdTask["Fk_EmployeeID"]!=null)
                            {
                                notify.Fk_EmployeeID = Convert.ToInt32(rdTask["Fk_EmployeeID"]);

                            }

                            if (OasisConnection.State==ConnectionState.Open)
                            {
                                OasisConnection.Close();

                            }
                        }

                    }
                   
                  
                }
            }
            return View(notify);
        }

       
        [HttpPost]
        public ActionResult Comments(string Comment)
        {
            OasisConnectionManager = ConfigurationManager.ConnectionStrings["OasisConnectionString"].ConnectionString;
            OasisConnection = new SqlConnection(OasisConnectionManager);
            var query = "insert into Comments (Fk_commentor_ID,Fk_task_ID,comments,DateCommented,commenter) values(@Fk_commentor_ID,@Fk_task_ID,@comments,@DateCommented,@commenter)";
            SqlCommand insertcommand = new SqlCommand(query, OasisConnection);
            insertcommand.Parameters.AddWithValue("@Fk_commentor_ID", Convert.ToInt32(Session["id"]));
            insertcommand.Parameters.AddWithValue("@Fk_task_ID", Convert.ToInt32( Session["taskID"]));
            insertcommand.Parameters.AddWithValue("@comments", Comment);
            insertcommand.Parameters.AddWithValue("@DateCommented", DateTime.Now);
            insertcommand.Parameters.AddWithValue("@commenter", @Session["username"]);

            OasisConnection.Open();
            int results = insertcommand.ExecuteNonQuery();
            return RedirectToAction("taskProgress", new { notificationID = Convert.ToInt32(Session["notificationID"]) } );
        }


        public ActionResult Task()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Task(string TaskDetail)
        {
            OasisConnectionManager = ConfigurationManager.ConnectionStrings["OasisConnectionString"].ConnectionString;

            OasisConnection = new SqlConnection(OasisConnectionManager);

            var SelectGetQuery = "select * from GetTask where Fk_NoticationID='" + Convert.ToInt32(Session["notificationID"]) + "'";
            SqlCommand selecttcommand = new SqlCommand(SelectGetQuery, OasisConnection);

            OasisConnection.Open();

            SqlDataReader rdTask = selecttcommand.ExecuteReader();

            if(rdTask.Read())
            {
                var query = "insert into Tasks (TaskDetail,dateAssigned,DueDate,TaskStatus,Fk_GetTask) values(@TaskDetail,@dateAssigned,@DueDate,@TaskStatus,@Fk_GetTask)";
                SqlCommand insertcommand = new SqlCommand(query, OasisConnection);
                insertcommand.Parameters.AddWithValue("@TaskDetail", TaskDetail);
                insertcommand.Parameters.AddWithValue("@TaskStatus", "Accepted");
                insertcommand.Parameters.AddWithValue("@dateAssigned", DateTime.Now);
                insertcommand.Parameters.AddWithValue("@DueDate", DateTime.Now.AddDays(7));
                insertcommand.Parameters.AddWithValue("@Fk_GetTask", Convert.ToInt32(rdTask["id"]));


                Session["taskID"] = Convert.ToInt32(rdTask["id"]);


                if (OasisConnection.State==ConnectionState.Open)
                {
                    OasisConnection.Close();
                    OasisConnection.Open();
                    int results = insertcommand.ExecuteNonQuery();


                    if (results > 0)
                    {

OasisCommunicationManagement/Controllers/TasksController.cs
using BusinessLogic;
using DataAccessLayer.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace OasisCommunicationManagement.Controllers
{
    public class TasksController : Controller
    {
        // GET: Tasks
        public ActionResult NewTask(string tasktype)
        {
            Session.Remove("tasktype");
            Session["tasktype"] = tasktype;


            return View();
        }

     


       
        [HttpPost]
        public ActionResult OasisTask(string NewTask)
        {


            Task MynewTask = new Task("Insert_no_model");

            MynewTask.NewTask(Convert.ToInt32(Session["userId"]), NewTask);


            return RedirectToAction("GetTask");
;
        }
        public ActionResult TaskColobaration()
        {
            Task notifications = new Task("Select");

            List<Tasks> pNotiList = new List<Tasks>();


            pNotiList = notifications.GetTasks();


            List<Users> userManager = new List<Users>();


            UserAccounts AccountList = new UserAccounts("Select");

            Session["userdetails"] = AccountList.Login();

            return View(pNotiList);

        }



        public ActionResult GetTask()
        {
            Task notifications = new Task("Select");

            List<Tasks> pNotiList = new List<Tasks>();

            pNotiList = notifications.GetTasks();

            Session.Remove("taskDetail");

            return View(pNotiList);


        }

        static  int  Taskid;
        static    List<Comments> pNotiList = new List<Comments>();

        public ActionResult Colaboration(int TaskId)
        {
            Taskid = TaskId;
            Session.Remove("taskID");

                
            Coloboration coloborations = new Coloboration("Select");

            pNotiList = coloborations.GetComments(TaskId);
            Session["taskID"] = TaskId;
            return View(pNotiList);
        }


        [HttpPost]
        public ActionResult MyColaboration(string Comment)
        {

            Coloboration coloborations = new Coloboration("Insert");

            coloborations.SendCollab(Convert.ToInt32(Session["userId"]), Taskid, Comment, Session["taskDetail"].ToString());

            return RedirectToAction("Colaboration", new { Taskid = Taskid }); ;
        }


        public ActionResult AddNotification(int TaskID)
        {

            Task Mytask = new Task("Select");
            
             Session.Remove("taskID");


            Tasks t = new Tasks();


            List<Tasks> TasksValues = Mytask.GetTasks();


            foreach (var myt in TasksValues)
            {
                if(myt.id== TaskID)
                {
                    t = myt;
                }
            }
            Session["taskID"] = TaskID;


            return View(t);
        }


        [HttpPost]
        public ActionResult AddNotification(string Notification)
        {
            NotificationsDisplay notifications = new NotificationsDisplay();
            notifications.CreateAnotification("Has finished the task New Data " +  Notification  , "Manager");
            return RedirectToAction("Index", "Home");
        }






        static int EditTaskID;
        public ActionResult UpdateTask(int TaskID)
        {
            EditTaskID = TaskID;
            Session.Remove("EditaskID");

            if(Session["UserRole"].ToString()== "ProccessMaintananceEmployee")
            {
                return RedirectToAction("AddNotification", new { TaskID = TaskID });

            }
            else
            {
                Task updateTask = new Task("Update");

                updateTask.Update(TaskID);


                return RedirectToAction("GetTask");

            }

        
        }


        public ActionResult EmployeeDailyTask(int UserID)
        {

            return View();
        }

        public ActionResult ManagementCheckList()
        {

            return View();
        }


        [HttpPost]
        public ActionResult ManagementCheckListB(
            decimal _4_Softner,
           decimal _5_1_Micron_Preasure,
           decimal _6_Membrane_Preasure,
           decimal _7_Flow_Rate_RAW,
             decimal _2_PF_5_Micron,
           decimal _1_PF_10_Micron,
           decimal TDs_Main,
           decimal TDs_clean,
           decimal _3_Sand_Filter


            )
        {
            CheckList checkList = new CheckList("InsertB");
            checkList.AddcheckListB(
               _4_Softner,
            _5_1_Micron_Preasure,
            _6_Membrane_Preasure,
            _7_Flow_Rate_RAW,
              _2_PF_5_Micron,
            _1_PF_10_Micron,
            TDs_Main,
            TDs_clean,
            _3_Sand_Filter);


            return RedirectToAction("ManagementCheckList");
        }

        public ActionResult GetCheckList()
        {
            List<ManagementCheckList> managementCheckLists = new List<ManagementCheckList>();
            CheckList checkList = new CheckList("Select");
            managementCheckLists = checkList.GetManagementCheckLists();
            return View(managementCheckLists);
        }

        static int listID;
        public ActionResult EditCheckList(int ChecklistID)
        {
            listID = ChecklistID;

            return View();
        }
        [HttpPost]
        public ActionResult EditCheckList(decimal _4_Softner = 0,
           decimal _5_1_Micron_Preasure = 0,
           decimal _6_Membrane_Preasure = 0,
           decimal _7_Flow_Rate_RAW = 0,
           string _8_Flow_Rate_Clean = "",
           string _9_Pump_Functional = "",
           decimal Conductive = 0,
           decimal Clean_Water_Meter_Reading = 0,
           decimal Litres_Purified = 0,
            decimal _3_Sand_Filter = 0,
           decimal _2_PF_5_Micron = 0,
           decimal _1_PF_10_Micron = 0,
           decimal Clean_tank_level = 0,
           decimal Mun_Tank_level = 0,
           string Silcone_Crystal_Color ="",
           string Ozone = "",
           decimal TDs_Main = 0,
           decimal TDs_clean = 0)
        {
            List<ManagementCheckList> managementCheckLists = new List<ManagementCheckList>();
            CheckList checkList = new CheckList();


            checkList.UpdateString
                (listID,
               
                _4_Softner,
            _5_1_Micron_Preasure,
            _6_Membrane_Preasure,
            _7_Flow_Rate_RAW,
            _8_Flow_Rate_Clean,
            _9_Pump_Functional,
            Conductive,
            Clean_Water_Meter_Reading,
            Litres_Purified,

              _2_PF_5_Micron,
            _1_PF_10_Micron,
            Clean_tank_level,
            Mun_Tank_level,
            Silcone_Crystal_Color,
            Ozone,
            TDs_Main,
            TDs_clean,
            _3_Sand_Filter);


            return RedirectToAction("GetCheckList");
        }


        public ActionResult Delete(int ChecklistID)
        {
            CheckList CheckLists = new CheckList("Delete");




            DialogResult dr = MessageBox.Show("Are you sure to delete row?", "Confirmation", MessageBoxButtons.YesNo);
            if (dr == DialogResult.Yes)
            {
                CheckLists.Delete(ChecklistID);
                return RedirectToAction("GetCheckList");

            }
            else if (dr == DialogResult.No)
            {
            }


            return RedirectToAction("GetCheckList");



        }
    }

 
   
}

OasisCommunicationManagement/Views/ProductionEmployees/Index.cshtml
@model IEnumerable<OasisCommunicationManagement.Models.notificationModel>

@{
    ViewBag.Title = "just";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

@using OasisCommunicationManagement.Models;
@using System.Configuration;
@using System.Data;
@using System.Data.SqlClient;



<div class="container">

    <hr>
    <div class="row">

        <div class="col-sm-9 col-md-10">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#home" data-toggle="tab">
                        <span class="glyphicon glyphicon-inbox">
                        </span>Notification center
                    </a>
                </li>
            </ul>
            <!-- Tab nes -->



            <div class="tab-content">
                <div id="home">
                    <div class="list-group">


                        @foreach (var item in Model)
                        {

                            <a href="@Url.Action("NotificationDetail", "ProductionEmployees", new { NotificationID =item.id })" class="list-group-item">

                                <span class="glyphicon glyphicon-star-empty"></span><span class="name" style="min-width: 120px;
                                             display: inline-block;"></span> <span class="">@item.Notification</span>
                                            <span class="text-muted" style="font-size: 11px;"></span> <span class="badge">Select to View Task Progress      @item.datesent    </span> <span class="pull-right">

                                            </span>
                                        </a>


                                    }
                    </div>
                </div>

                <div class="tab-pane fade in" id="messages">
                    ...
                </div>

            </div>


        </div>
    </div>
</div>

OasisCommunicationManagement/Views/ProductionEmployees/StartTask.cshtml
@{
    ViewBag.Title = "StartTask";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<h2>StartTask</h2>

OasisCommunicationManagement/Views/ProductionEmployees/Task.cshtml
@{
    ViewBag.Title = "Task";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<h2>Task</h2>

<div class="row">
    <div class="col-md-4">
        <!-- general information panel -->
        <div class="panel panel-default">
            <h6>enter task detai</h6>
            <div class="panel-body">
                <div class="space-child-divs">

                 

                    <form method="post" action="Task">

                        <div class="input-group">
                            <input style="width : 150px;height:55px;margin:0 " ;type="text" name="TaskDetail" placeholder=" Assign" class="form-control primary">
                            <br />
                            <div>
                                <span class="input-group-btn">
                                    <button style="width : 100px;height:55px;margin:0;" class="btn btn-primary" type="submit" name="Send" value="send message">Assign </button>
                                </span>
                            </div>
                            <br />
                            <hr />
                            <div>
                                <span class="input-group-btn">
                                    <a style="width : 100px;height:55px;margin:0;" class="btn btn-primary" href="../Manager/inbox">Back </a>
                                </span>

                            </div>


                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>

OasisCommunicationManagement/Views/ProductionEmployees/taskProgress.cshtml
@model OasisCommunicationManagement.Models.TaskModel

@{
    ViewBag.Title = "taskProgress";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

@using OasisCommunicationManagement.Models;
@using System.Configuration;
@using System.Data;
@using System.Data.SqlClient;

<div class="container">

    <hr>
    <div class="row">

        <div class="col-sm-9 col-md-10">
            <!-- Nav tabs -->




            <div class="tab-content">
                <div id="home">
                    <div class="list-group">



                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title">Task details</h3>

                                        <div class="card-tools">

                                        </div>
                                    </div>
                                    <!-- /.card-header -->
                                    <div class="card-body table-responsive p-0" ;">
                                        <form method="Post" action="UpdateTask">
                                            <table class="table table-head-fixed text-nowrap">
                                                <thead>
                                                    <tr>
                                                        <th>ID</th>
                                                        <th>Task Details</th>
                                                        <th>Date Assigned</th>
                                                        <th>Due date</th>
                                                        <th>Status</th>

                                                        <th>Action</th>


                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @{
                                                        Session["taskID"] = Model.id;

                                                        if (Model.TaskStatus == "Accepted")
                                                        {

                                                            <tr>
                                                                <td>@Model.id</td>
                                                                <td>@Model.Taskdetail</td>
                                                                <td>@Model.dateAssigned</td>
                                                                <td>@Model.DueDate</td>
                                                                <td><span class="tag tag-success">@Model.TaskStatus</span></td>
                                                                <td> Task not intitialized <a href="@Url.Action("StartTask", "ProductionEmployees", new { TaskID =Model.id })">Start task</a></td>
                                                            </tr>
                                                        }
                                                        else
                                                        {
                                                            if (Convert.ToInt32(Session["id"]) == Model.Fk_EmployeeID)
                                                            {
                                                                <tr>
                                                                    <td>@Model.id</td>
                                                                    <td>@Model.Taskdetail</td>
                                                                    <td>@Model.dateAssigned</td>
                                                                    <td>@Model.DueDate</td>

                                                                    <td><span class="tag tag-success">@Model.TaskStatus</span></td>



                                                                    <td><input type="text" name="NewTask" id="NewTask" placeholder="Enter new task progress" class="form-control"> Task started <button type="submit"> update task</button></td>
                                                                </tr>
                                                            }
                                                            else
                                                            {
                                                                <tr>
                                                                    <td>@Model.id</td>
                                                                    <td>@Model.Taskdetail</td>
                                                                    <td>@Model.dateAssigned</td>
                                                                    <td>@Model.DueDate</td>
                                                                    <td><span class="tag tag-success">@Model.TaskStatus</span></td>
                                                                    <td>Task has  been >@Model.Taskdetail you cannot make an action, comment for updates </td>
                                                                </tr>

                                                            }



                                                        }


                                                    }





                                                </tbody>



                                            </table>
                                        </form>

                                        <hr />
                                        <form action="Comments" method="post">
                                            <div>

                                                <textarea class="form-control" name="Comment" id="Comment" rows="3" placeholder="Enter ..."></textarea>
                                                <br />
                                                <button type="submit" style="width:80px" class="btn btn-block btn-secondary btn-lg">Comment</button>
                                                <br />
                                                <a style="width:80px" class="btn btn-danger btn-sm" href="../productionEmployees/index">close</a>
                                            </div>

                                        </form>
                                    </div>

                                    <br />
                                    <hr />
                                    <p>Comments</p>


                                    @{


                                        string OasisConnectionManager;
                                        SqlConnection OasisConnection;

                                        OasisConnectionManager = ConfigurationManager.ConnectionStrings["OasisConnectionString"].ConnectionString;

                                        OasisConnection = new SqlConnection(OasisConnectionManager);

                                        DataTable dataTable = new DataTable();
                                        OasisConnection.Open();

                                        var query = "select * from Comments where Fk_task_ID='" + Convert.ToInt32(Model.id) + "'";
                                        SqlCommand SelectCommand = new SqlCommand(query, OasisConnection);

                                        using (SqlDataReader rd = SelectCommand.ExecuteReader())
                                        {


                                            while (rd.Read())
                                            {
                                                <div class="timeline-item">
                                                    <span class="time"><i class="fas fa-clock"></i>@rd["DateCommented"]</span>
                                                    <h5 class="timeline-header">@rd["commenter"] </h5>
                                                    <div class="timeline-body">
                                                       @rd["comments"]
                                                    </div>

                                                </div>

                                            

                                        }
                                    }

                                    }

                                    <!-- /.card-body -->
                                    <br />

                                    
                                </div>
                                <!-- /.card -->
                            </div>
                        </div>


                    </div>
                </div>

                <div class="tab-pane fade in" id="messages">
                    ...
                </div>

            </div>


        </div>
    </div>
</div>